In [2]:
import pandas as pd
import numpy as np

In [21]:
origin_df= pd.DataFrame({'A': ['강다솜','김나영','이강욱'],'B': ['A','A','A'],'C': [1,2,3]})
update_df=pd.DataFrame({'A': ['강다솜','김나영','이강욱'],'B': ['A','A','B'],'C': [10,20,30]})

In [22]:
origin_df

A  B  C
0  강다솜  A  1
1  김나영  A  2
2  이강욱  A  3

In [23]:
update_df

A  B   C
0  강다솜  A  10
1  김나영  A  20
2  이강욱  B  30

In [24]:
update_df.set_index(['A','B'])

C
A   B    
강다솜 A  10
김나영 A  20
이강욱 B  30

In [25]:
origin_df.set_index(['A','B'])

C
A   B   
강다솜 A  1
김나영 A  2
이강욱 A  3

In [26]:
origin_df.reset_index()

index    A  B  C
0      0  강다솜  A  1
1      1  김나영  A  2
2      2  이강욱  A  3

In [27]:
update_df.reset_index()

index    A  B   C
0      0  강다솜  A  10
1      1  김나영  A  20
2      2  이강욱  B  30

In [28]:
update_df.set_index(['A','B'],inplace=True)
origin_df.set_index(['A','B'],inplace=True)

In [29]:
pd.merge(origin_df,update_df,how='outer')

C
0   1
1   2
2   3
3  10
4  20
5  30

In [30]:
df=pd.read_csv('http://bit.ly/3RhoNho')

C:\Users\user\AppData\Local\Temp\ipykernel_6456\373930061.py:1: DtypeWarning: Columns (5,6,9) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv('http://bit.ly/3RhoNho')


In [67]:
df.drop(columns=df.columns[-1],inplace=True)

In [68]:
df.replace(np.nan,0)

번호                    도서명                저자    출판사  발행년도  \
0            1                인공지능과 흙            김동훈 지음    민음사  2021   
1            2           가짜 행복 권하는 사회            김태형 지음   갈매나무  2021   
2            3  나도 한 문장 잘 쓰면 바랄 게 없겠네            김선영 지음   블랙피쉬  2021   
3            4                예루살렘 해변  이도 게펜 지음, 임재희 옮김  문학세계사  2021   
4            5  김성곤의 중국한시기행 : 장강·황하 편            김성곤 지음    김영사  2021   
...        ...                    ...               ...    ...   ...   
401677  401678                韓國現代詩大系            채만묵 編著  한국문화사  1996   
401678  401679                  뉴 웨이브        제임스 모나코 지음    한나래  1996   
401679  401680           (최인훈 장편소설)화두            최인훈 지음    민음사  1994   
401680  401681           독일 문학과 세계 문학            吳漢鎭 編著     벽호  1995   
401681  401682             참으로 소중한 생각            김일상 지음    동문사  1995   

                 ISBN          세트 ISBN 부가기호  권   주제분류번호  도서권수  대출건수  
0       9788937444319                0    0  0        0     1     0  
1       9791190123969                0    0  0        0     1     0  
2       9788968332982                0    0  0        0     1     0  
3       9788970759906                0    0  0        0     1     0  
4       9788934990833                0    0  0        0     1     0  
...               ...              ...  ... ..      ...   ...   ...  
401677  9788977352971  9788977352988.0    0  3  811.608     1     0  
401678  9788985367448  9788985367424.0    0  2   688.04     1     0  
401679  9788937401596  9788937401589.0    0  2    813.6     1     0  
401680  9788947700368  9788947700405.0    0  3   809.05     2     0  
401681  9788970610092  9788970610092.0    0  1    814.6     0     0  

[401682 rows x 12 columns]

In [69]:
origin_df.replace('이강욱','강욱')
origin_df.replace(3,30)

C
A   B    
강다솜 A   1
김나영 A   2
이강욱 A  30

In [71]:
df_=df.copy()
df_.fillna(0,inplace=True)
df=[df.도서명.fillna(0).str.contains('인공지능'),['도서명']]

In [72]:
df.도서명.replace(np.nan,'없음',inplace=True)

AttributeError: 'list' object has no attribute '도서명'

In [45]:
df.loc[df.도서명.str.contains('인공지능'),['도서관']]

KeyError: "None of [Index(['도서관'], dtype='object')] are in the [columns]"

In [73]:
person=np.random.choice(['female','male'],size=10000)

In [74]:
person

array(['female', 'male', 'male', ..., 'female', 'female', 'male'],
      dtype='<U6')

In [75]:
score=np.random.randint(50,100,size=(10000,4))

In [76]:
columns=['gender','korea','english','math','science']

In [77]:
person=pd.DataFrame(person)

In [78]:
person=pd.concat([person,pd.DataFrame(score)],axis=1)
person.columns=columns
person

gender  korea  english  math  science
0     female     53       55    75       60
1       male     80       62    51       77
2       male     90       56    97       89
3       male     67       56    70       97
4     female     89       92    64       97
...      ...    ...      ...   ...      ...
9995    male     62       50    68       73
9996    male     67       70    55       73
9997  female     65       91    66       56
9998  female     86       86    81       54
9999    male     88       80    61       57

[10000 rows x 5 columns]

In [92]:
person=np.random.choice(['female','male'],size=10000)
score=np.random.randint(50,100,size=(10000,4))
columns=['gender','korea','english','math','science']
person=pd.DataFrame(person)

In [93]:
person=pd.DataFrame(np.c_[person,score],columns=columns)
person

gender korea english math science
0     female    93      56   87      76
1     female    93      83   98      87
2       male    58      64   52      76
3       male    70      53   65      81
4     female    93      90   68      93
...      ...   ...     ...  ...     ...
9995  female    88      72   74      87
9996    male    84      81   84      98
9997    male    62      86   70      71
9998    male    95      76   94      76
9999  female    74      64   51      74

[10000 rows x 5 columns]

In [212]:
person.iloc[:,1:].astype({'korea'==int,'english'==int,'math'==int,'science'==int})

NameError: name 'int32' is not defined

In [97]:
#총점,평균
total=person.korea+person.english+person.math+person.science
avg=total/4

In [98]:
total

0       312
1       361
2       250
3       269
4       344
       ... 
9995    321
9996    347
9997    289
9998    341
9999    263
Length: 10000, dtype: object

In [116]:
col_total=[]
for i in range(person.shape[1]-1): #-1은 gender의 값을 삭제하기 위해서
    col_total.append(person.iloc[:,i+1].sum())

In [108]:
# 90이상은 A, 80이상은 B,70 이상은 C, 나머지는 D
grade=np.where(avg>=90,'A',np.where(avg>=80,'B',np.where(avg>=70,'C','D')))

In [109]:

#다른 방법
total=[]
for i in range(person.shape[0]):
    total.append(person.iloc[i,1:].sum())
#다른 방법    
total=[]
for i in range(person.shape[0]):
    total.append(sum(person.iloc[i,1:]))
#다른 방법
total=person.iloc[:,1:].apply(sum,1)
#다른 방법
avg=person.iloc[:,1:].apply(np.mean,1)
#이건 다른 것


In [110]:
person['total']=total
person['avg']=avg
person['grade']=grade

In [111]:
#순서정렬
np.sort(person.avg)[::-1] #원래 작은 수를 먼저 해서 정렬하는데 ::-1로 큰 거부터함

array([95.75, 95.5 , 95.25, ..., 53.  , 53.  , 52.  ])

In [118]:
person.loc[person.total==383,'korea']

8509    96
Name: korea, dtype: object

In [138]:
person.iloc[person.total.argmax(),'korea'] #argmax는 큰 수 하나의 인덱스 구함. 그리고 이건 인덱스와 korea가 겹치는 값이 나오는 것

ValueError: Location based indexing can only have [integer, integer slice (START point is INCLUDED, END point is EXCLUDED), listlike of integers, boolean array] types

In [135]:
#제일 잘한 과목 점수 구하기
# person.iloc[0,1:5].max()
# person.iloc[:,1:5].apply(np.max,1)
np.argmax(person.iloc[0,1:5])

0

In [139]:
#제일 잘한 과목명 쓰기
bs=np.argmax(person.iloc[0,1:5]) #0은 구하고 싶은 행을 적으면 됨, 이건 제일 잘한 과목이 어디있는 가를 찾는 것
person.columns[1:5][bs] #어디(bs)를 찾은 걸 그 위치를 넣어 컬럼명을 찾음
def find_subject(x):
    bs=np.argmax(x)
    return person.columns[1:5][bs]

In [177]:
person.rename(columns={'best_subject':'best_score'},inplace=True)

In [178]:
person['best_score']=person.iloc[:,1:5].apply(np.max,1)
person

gender korea english math science  total    avg grade  best_score  \
0     female    93      56   87      76    312  78.00     C          93   
1     female    93      83   98      87    361  90.25     A          98   
2       male    58      64   52      76    250  62.50     D          76   
3       male    70      53   65      81    269  67.25     D          81   
4     female    93      90   68      93    344  86.00     B          93   
...      ...   ...     ...  ...     ...    ...    ...   ...         ...   
9995  female    88      72   74      87    321  80.25     B          88   
9996    male    84      81   84      98    347  86.75     B          98   
9997    male    62      86   70      71    289  72.25     C          86   
9998    male    95      76   94      76    341  85.25     B          95   
9999  female    74      64   51      74    263  65.75     D          74   

      best_score  best_score  
0             93          93  
1             98          98  
2             76          76  
3             81          81  
4             93          93  
...          ...         ...  
9995          88          88  
9996          98          98  
9997          86          86  
9998          95          95  
9999          74          74  

[10000 rows x 11 columns]

In [167]:
#잘한 과목명 점수 순서대로 쓰기
'-->'.join(person.columns[1:5][np.argsort(person.iloc[0,1:5])[::-1]])

'korea-->math-->science-->english'

In [168]:
#잘한 과목명 점수 순서대로 쓰기
def subject_order(x):
    return '-->'.join(person.columns[1:5][np.argsort(person.iloc[x,1:5])[::-1]])

In [169]:
subject_order(0)

'korea-->math-->science-->english'

In [170]:
person['grade_order']= person.iloc[:,1:5].apply(subject_order,1)

IndexError: .iloc requires numeric indexers, got [93 56 87 76]

In [180]:
person['best_subject']=person.iloc[:,1:5].apply(find_subject,1)

In [195]:
#groupby : split(column을 기준으로), apply, combine - groupby는 데이터프레임만
group_df=pd.DataFrame(columns=['best_subject','korea','english'])
for i in person.best_subject.unique():
    tmp_df=person.loc[person.best_subject==i,:].sum()[[i,'korea','english']]
    tmp_df = pd.DataFrame({'best_subject':[i],'korea':tmp_df.values[[0]], 'english':tmp_df.values[[1]]})
    group_df=pd.concat([group_df,tmp_df])
group_df

best_subject   korea english
0        korea  229092  229092
0         math  226079  175287
0      science  217960  168400
0      english  222496  171122

In [196]:
#다른 방법
person.groupby(['best_subject']).sum()[['korea','english']]

C:\Users\user\AppData\Local\Temp\ipykernel_6456\3435855952.py:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  person.groupby(['best_subject']).sum()[['korea','english']]


KeyError: "None of [Index(['korea', 'english'], dtype='object')] are in the [columns]"

In [ ]:
person.groupby(['grade_order']).count().korea
person.groupby(['gender','grade']).std() #std()는 표준편차를 구하는 것
person.groupby(['gender','grade']).agg(['mean','sum','count'])
person.groupby(['gender','grade']).agg(['mean','sum','count']).korea['count'].sum() #count가 10000이 맞는 지 확인하기 위해 적음

In [ ]:
#가장 잘한 과목이 영어와 국어인 데이터를 제외하고 남자 여자의 영어, 수학의 평균을 구하면?
person.loc[~((person.best_subject=='korea')|(person.best_subject=='english'))].groupby(['gender'])

In [ ]:
#가장 잘한 과목이 영어와 국어, 과학 데이터를 제외하고 남자 여자의 영어, 수학의 평균을 구하면?

In [ ]:
import warnings
warnings.filterwarnings(action='ignore')
person.groupby(['best_subject']).mean([['korea','english']])

In [183]:
person.groupby(['best_subject']).mean([['korea','english']])

total        avg  best_score  best_score  best_score
best_subject                                                           
english       297.400402  74.350100   89.355823   89.355823   89.355823
korea         298.296686  74.574172   89.314620   89.314620   89.314620
math          298.302621  74.575655   89.785147   89.785147   89.785147
science       297.772971  74.443243   89.806345   89.806345   89.806345

In [185]:
np.argmax(person.groupby(['gender','best_subject']).count()[['korea']].loc['female','korea'])

0

In [172]:
x=np.random.randint(1,10,5)

In [173]:
x

array([6, 3, 5, 5, 3])

In [174]:
np.argsort(x) #작은 수부터 먼저 해서 인덱스를 정렬

array([1, 4, 2, 3, 0], dtype=int64)

In [201]:
person.describe() #수치형
person[['gender','best_subject','grade_order','grade']].describe() #object type

KeyError: "['grade_order'] not in index"

In [204]:
"""
selet korea, english
from person
where best_subject in ('english','korea')
group by gender
"""

"\nselet korea, english\nfrom person\nwhere best_subject in ('english','korea')\ngroup by gender\n"

In [205]:
person.describe()

total           avg    best_score    best_score    best_score
count  10000.000000  10000.000000  10000.000000  10000.000000  10000.000000
mean     297.947900     74.486975     89.562700     89.562700     89.562700
std       28.801843      7.200461      8.151044      8.151044      8.151044
min      208.000000     52.000000     56.000000     56.000000     56.000000
25%      278.000000     69.500000     85.000000     85.000000     85.000000
50%      298.000000     74.500000     92.000000     92.000000     92.000000
75%      318.000000     79.500000     96.000000     96.000000     96.000000
max      383.000000     95.750000     99.000000     99.000000     99.000000

In [ ]:
#x는 내가 고른 것, n은 숫자의 범위
(x/n) & ((n-x)/n)

In [208]:
x=np.arange(1,100)

In [209]:
n=100
prob=[]
for i in x:
    prob.append(i*(100-i)/10000)
    

In [211]:
plt.plot(x,prob)

NameError: name 'plt' is not defined