In [3]:
import numpy as np

In [4]:
np_arr1=np.array([1,2,3])
print(np_arr1)

[1 2 3]


In [5]:
np_arr1=np.array([1,2.0,'3'])
print(np_arr1)

['1' '2.0' '3']


In [10]:
np.inf
# inf는 무한이라는 뜻

inf

In [11]:
np.NINF
#음의 무한이라는 뜻

-inf

In [18]:
[abs(i) for i in [-1, 1, 3, 1]]

[1, 1, 3, 1]

In [21]:
np.any([0.1,0.2,0.3])

True

In [22]:
arr=np.array([1,2,3,4])
arr.shape
np.append(arr,10)

array([ 1,  2,  3,  4, 10])

In [24]:
n_range=np.arange(1,11)
r=range(1,11)

In [56]:
import pandas as pd
df=pd.DataFrame(np.random.randint(1,20,size=(10000000,5)))

In [57]:
np.sum(df.values)

499987987

In [58]:
df.apply(sum,1)

0          64
1          45
2          26
3          57
4          59
           ..
9999995    39
9999996    52
9999997    44
9999998    48
9999999    42
Length: 10000000, dtype: int64

In [59]:
def xx(x):
    return np.sum(np.where(x%2==0,1,0))

In [60]:
a=df.apply(xx,1)
a

KeyboardInterrupt: 

In [ ]:
df.apply(lambda x : np.sum(np.where(x%2==0,1,0)),1)

In [ ]:
a=np.apply_along_axis(xx,1,df)
a

In [46]:
x = np.array([2,1,2,1,2,2])
np.where(x==1, True, False)

array([False,  True, False,  True, False, False])

In [63]:
import math
math.sin(np.pi/2)
np.sin(np.pi/2)

1.0

In [66]:
np.argmax([2,3,4])

2

In [67]:
np.argmin([2,3,4])

0

In [69]:
np.argsort([2,3,4,6,5]) # 제일 중요

array([0, 1, 2, 4, 3], dtype=int64)

In [ ]:
np.argsort(arr) # 제일 중요
np.argmax(arr) # 2번째로 중요
np.argmin(arr) # 2번째로 중요
np.min(arr) # 3번째로 중요
np.max(arr) # 3번째로 중요
np.sort(arr) # 4번째로 중요

In [75]:
# round([7/96, 5/13],3) round는 리스트 형식이 안 됨
np.around([7/96, 5/13],3)

array([0.073, 0.385])

In [76]:
m1=np.random.randint(1,10,size=(2,3))
m2=np.random.randint(1,10,size=(3,2))
# np.asmatrix()

In [77]:
m3=np.asmatrix(m1)
m4=np.asmatrix(m2)

In [78]:
np.dot(m1,m2)

array([[44, 49],
       [27, 23]])

In [79]:
np.dot(m3,m4)

matrix([[44, 49],
        [27, 23]])

In [80]:
m3*m4

matrix([[44, 49],
        [27, 23]])

In [81]:
import sys
sys.getsizeof([1,2,3])

88

In [82]:
r=range(1,100)

In [83]:
sys.getsizeof(r)

48

In [84]:
r1=list(range(1,1000000))

In [85]:
sys.getsizeof(r1)

8000056